/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SetupImport } from './routes/setup'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as StockIndexImport } from './routes/stock/index'
import { Route as StickIndexImport } from './routes/stick/index'
import { Route as StatsIndexImport } from './routes/stats/index'
import { Route as ConnectIndexImport } from './routes/connect/index'
import { Route as CashIndexImport } from './routes/cash/index'

// Create/Update Routes

const SetupRoute = SetupImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StockIndexRoute = StockIndexImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRoute,
} as any)

const StickIndexRoute = StickIndexImport.update({
  id: '/stick/',
  path: '/stick/',
  getParentRoute: () => rootRoute,
} as any)

const StatsIndexRoute = StatsIndexImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectIndexRoute = ConnectIndexImport.update({
  id: '/connect/',
  path: '/connect/',
  getParentRoute: () => rootRoute,
} as any)

const CashIndexRoute = CashIndexImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupImport
      parentRoute: typeof rootRoute
    }
    '/cash/': {
      id: '/cash/'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/': {
      id: '/connect/'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectIndexImport
      parentRoute: typeof rootRoute
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/stick/': {
      id: '/stick/'
      path: '/stick'
      fullPath: '/stick'
      preLoaderRoute: typeof StickIndexImport
      parentRoute: typeof rootRoute
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash': typeof CashIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/stats': typeof StatsIndexRoute
  '/stick': typeof StickIndexRoute
  '/stock': typeof StockIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash': typeof CashIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/stats': typeof StatsIndexRoute
  '/stick': typeof StickIndexRoute
  '/stock': typeof StockIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash/': typeof CashIndexRoute
  '/connect/': typeof ConnectIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/stick/': typeof StickIndexRoute
  '/stock/': typeof StockIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/cash'
    | '/connect'
    | '/stats'
    | '/stick'
    | '/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/cash'
    | '/connect'
    | '/stats'
    | '/stick'
    | '/stock'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/cash/'
    | '/connect/'
    | '/stats/'
    | '/stick/'
    | '/stock/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  CashIndexRoute: typeof CashIndexRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  StickIndexRoute: typeof StickIndexRoute
  StockIndexRoute: typeof StockIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  CashIndexRoute: CashIndexRoute,
  ConnectIndexRoute: ConnectIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  StickIndexRoute: StickIndexRoute,
  StockIndexRoute: StockIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/setup",
        "/cash/",
        "/connect/",
        "/stats/",
        "/stick/",
        "/stock/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx"
    },
    "/cash/": {
      "filePath": "cash/index.tsx"
    },
    "/connect/": {
      "filePath": "connect/index.tsx"
    },
    "/stats/": {
      "filePath": "stats/index.tsx"
    },
    "/stick/": {
      "filePath": "stick/index.tsx"
    },
    "/stock/": {
      "filePath": "stock/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
