/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as StockAppposIndexRouteImport } from './routes/stock-apppos/index'
import { Route as StickIndexRouteImport } from './routes/stick/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as ConnectIndexRouteImport } from './routes/connect/index'
import { Route as CashIndexRouteImport } from './routes/cash/index'
import { Route as ConnectQuotesIndexRouteImport } from './routes/connect/quotes/index'
import { Route as ConnectInvoicesIndexRouteImport } from './routes/connect/invoices/index'
import { Route as ConnectQuotesNewRouteImport } from './routes/connect/quotes/new'
import { Route as ConnectInvoicesNewRouteImport } from './routes/connect/invoices/new'
import { Route as ConnectQuotesQuoteIdIndexRouteImport } from './routes/connect/quotes/$quoteId/index'
import { Route as ConnectQuotesQuoteIdEditRouteImport } from './routes/connect/quotes/$quoteId/edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAppposIndexRoute = StockAppposIndexRouteImport.update({
  id: '/stock-apppos/',
  path: '/stock-apppos/',
  getParentRoute: () => rootRouteImport,
} as any)
const StickIndexRoute = StickIndexRouteImport.update({
  id: '/stick/',
  path: '/stick/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectIndexRoute = ConnectIndexRouteImport.update({
  id: '/connect/',
  path: '/connect/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashIndexRoute = CashIndexRouteImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectQuotesIndexRoute = ConnectQuotesIndexRouteImport.update({
  id: '/connect/quotes/',
  path: '/connect/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectInvoicesIndexRoute = ConnectInvoicesIndexRouteImport.update({
  id: '/connect/invoices/',
  path: '/connect/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectQuotesNewRoute = ConnectQuotesNewRouteImport.update({
  id: '/connect/quotes/new',
  path: '/connect/quotes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectInvoicesNewRoute = ConnectInvoicesNewRouteImport.update({
  id: '/connect/invoices/new',
  path: '/connect/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectQuotesQuoteIdIndexRoute =
  ConnectQuotesQuoteIdIndexRouteImport.update({
    id: '/connect/quotes/$quoteId/',
    path: '/connect/quotes/$quoteId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectQuotesQuoteIdEditRoute =
  ConnectQuotesQuoteIdEditRouteImport.update({
    id: '/connect/quotes/$quoteId/edit',
    path: '/connect/quotes/$quoteId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash': typeof CashIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/stats': typeof StatsIndexRoute
  '/stick': typeof StickIndexRoute
  '/stock-apppos': typeof StockAppposIndexRoute
  '/stock': typeof StockIndexRoute
  '/connect/invoices/new': typeof ConnectInvoicesNewRoute
  '/connect/quotes/new': typeof ConnectQuotesNewRoute
  '/connect/invoices': typeof ConnectInvoicesIndexRoute
  '/connect/quotes': typeof ConnectQuotesIndexRoute
  '/connect/quotes/$quoteId/edit': typeof ConnectQuotesQuoteIdEditRoute
  '/connect/quotes/$quoteId': typeof ConnectQuotesQuoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash': typeof CashIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/stats': typeof StatsIndexRoute
  '/stick': typeof StickIndexRoute
  '/stock-apppos': typeof StockAppposIndexRoute
  '/stock': typeof StockIndexRoute
  '/connect/invoices/new': typeof ConnectInvoicesNewRoute
  '/connect/quotes/new': typeof ConnectQuotesNewRoute
  '/connect/invoices': typeof ConnectInvoicesIndexRoute
  '/connect/quotes': typeof ConnectQuotesIndexRoute
  '/connect/quotes/$quoteId/edit': typeof ConnectQuotesQuoteIdEditRoute
  '/connect/quotes/$quoteId': typeof ConnectQuotesQuoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash/': typeof CashIndexRoute
  '/connect/': typeof ConnectIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/stick/': typeof StickIndexRoute
  '/stock-apppos/': typeof StockAppposIndexRoute
  '/stock/': typeof StockIndexRoute
  '/connect/invoices/new': typeof ConnectInvoicesNewRoute
  '/connect/quotes/new': typeof ConnectQuotesNewRoute
  '/connect/invoices/': typeof ConnectInvoicesIndexRoute
  '/connect/quotes/': typeof ConnectQuotesIndexRoute
  '/connect/quotes/$quoteId/edit': typeof ConnectQuotesQuoteIdEditRoute
  '/connect/quotes/$quoteId/': typeof ConnectQuotesQuoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/cash'
    | '/connect'
    | '/stats'
    | '/stick'
    | '/stock-apppos'
    | '/stock'
    | '/connect/invoices/new'
    | '/connect/quotes/new'
    | '/connect/invoices'
    | '/connect/quotes'
    | '/connect/quotes/$quoteId/edit'
    | '/connect/quotes/$quoteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/cash'
    | '/connect'
    | '/stats'
    | '/stick'
    | '/stock-apppos'
    | '/stock'
    | '/connect/invoices/new'
    | '/connect/quotes/new'
    | '/connect/invoices'
    | '/connect/quotes'
    | '/connect/quotes/$quoteId/edit'
    | '/connect/quotes/$quoteId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/cash/'
    | '/connect/'
    | '/stats/'
    | '/stick/'
    | '/stock-apppos/'
    | '/stock/'
    | '/connect/invoices/new'
    | '/connect/quotes/new'
    | '/connect/invoices/'
    | '/connect/quotes/'
    | '/connect/quotes/$quoteId/edit'
    | '/connect/quotes/$quoteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  CashIndexRoute: typeof CashIndexRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  StickIndexRoute: typeof StickIndexRoute
  StockAppposIndexRoute: typeof StockAppposIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  ConnectInvoicesNewRoute: typeof ConnectInvoicesNewRoute
  ConnectQuotesNewRoute: typeof ConnectQuotesNewRoute
  ConnectInvoicesIndexRoute: typeof ConnectInvoicesIndexRoute
  ConnectQuotesIndexRoute: typeof ConnectQuotesIndexRoute
  ConnectQuotesQuoteIdEditRoute: typeof ConnectQuotesQuoteIdEditRoute
  ConnectQuotesQuoteIdIndexRoute: typeof ConnectQuotesQuoteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-apppos/': {
      id: '/stock-apppos/'
      path: '/stock-apppos'
      fullPath: '/stock-apppos'
      preLoaderRoute: typeof StockAppposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stick/': {
      id: '/stick/'
      path: '/stick'
      fullPath: '/stick'
      preLoaderRoute: typeof StickIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/': {
      id: '/connect/'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/': {
      id: '/cash/'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/quotes/': {
      id: '/connect/quotes/'
      path: '/connect/quotes'
      fullPath: '/connect/quotes'
      preLoaderRoute: typeof ConnectQuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/invoices/': {
      id: '/connect/invoices/'
      path: '/connect/invoices'
      fullPath: '/connect/invoices'
      preLoaderRoute: typeof ConnectInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/quotes/new': {
      id: '/connect/quotes/new'
      path: '/connect/quotes/new'
      fullPath: '/connect/quotes/new'
      preLoaderRoute: typeof ConnectQuotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/invoices/new': {
      id: '/connect/invoices/new'
      path: '/connect/invoices/new'
      fullPath: '/connect/invoices/new'
      preLoaderRoute: typeof ConnectInvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/quotes/$quoteId/': {
      id: '/connect/quotes/$quoteId/'
      path: '/connect/quotes/$quoteId'
      fullPath: '/connect/quotes/$quoteId'
      preLoaderRoute: typeof ConnectQuotesQuoteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/quotes/$quoteId/edit': {
      id: '/connect/quotes/$quoteId/edit'
      path: '/connect/quotes/$quoteId/edit'
      fullPath: '/connect/quotes/$quoteId/edit'
      preLoaderRoute: typeof ConnectQuotesQuoteIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  CashIndexRoute: CashIndexRoute,
  ConnectIndexRoute: ConnectIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  StickIndexRoute: StickIndexRoute,
  StockAppposIndexRoute: StockAppposIndexRoute,
  StockIndexRoute: StockIndexRoute,
  ConnectInvoicesNewRoute: ConnectInvoicesNewRoute,
  ConnectQuotesNewRoute: ConnectQuotesNewRoute,
  ConnectInvoicesIndexRoute: ConnectInvoicesIndexRoute,
  ConnectQuotesIndexRoute: ConnectQuotesIndexRoute,
  ConnectQuotesQuoteIdEditRoute: ConnectQuotesQuoteIdEditRoute,
  ConnectQuotesQuoteIdIndexRoute: ConnectQuotesQuoteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
