/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SetupImport } from './routes/setup'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as StockIndexImport } from './routes/stock/index'
import { Route as StickIndexImport } from './routes/stick/index'
import { Route as StatsIndexImport } from './routes/stats/index'
import { Route as SiteIndexImport } from './routes/site/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as InventoryAppposIndexImport } from './routes/inventory-apppos/index'
import { Route as ConnectIndexImport } from './routes/connect/index'
import { Route as CashIndexImport } from './routes/cash/index'
import { Route as SiteMenuImport } from './routes/site/menu'
import { Route as SiteCatalogueImport } from './routes/site/catalogue'
import { Route as SettingsUsersImport } from './routes/settings/users'
import { Route as SettingsSmtpImport } from './routes/settings/smtp'
import { Route as SettingsSecretsImport } from './routes/settings/secrets'
import { Route as SettingsCompaniesImport } from './routes/settings/companies'
import { Route as CashConfigImport } from './routes/cash/config'
import { Route as StockProduitsIndexImport } from './routes/stock/produits/index'
import { Route as StockMarquesIndexImport } from './routes/stock/marques/index'
import { Route as StockInventaireIndexImport } from './routes/stock/inventaire/index'
import { Route as StockFournisseursIndexImport } from './routes/stock/fournisseurs/index'
import { Route as StockCategoriesIndexImport } from './routes/stock/categories/index'
import { Route as ConnectQuotesIndexImport } from './routes/connect/quotes/index'
import { Route as ConnectOrdersIndexImport } from './routes/connect/orders/index'
import { Route as ConnectInvoicesIndexImport } from './routes/connect/invoices/index'
import { Route as ConnectCustomersIndexImport } from './routes/connect/customers/index'
import { Route as CashTicketsIndexImport } from './routes/cash/tickets/index'
import { Route as CashTerminalIndexImport } from './routes/cash/terminal/index'
import { Route as CashRapportZIndexImport } from './routes/cash/rapport-z/index'
import { Route as CashProductsIndexImport } from './routes/cash/products/index'
import { Route as ConnectQuotesNewImport } from './routes/connect/quotes/new'
import { Route as ConnectOrdersNewImport } from './routes/connect/orders/new'
import { Route as ConnectInvoicesNewImport } from './routes/connect/invoices/new'
import { Route as ConnectCustomersNewImport } from './routes/connect/customers/new'
import { Route as ConnectQuotesQuoteIdIndexImport } from './routes/connect/quotes/$quoteId/index'
import { Route as ConnectOrdersOrderIdIndexImport } from './routes/connect/orders/$orderId/index'
import { Route as ConnectInvoicesInvoiceIdIndexImport } from './routes/connect/invoices/$invoiceId/index'
import { Route as ConnectCustomersCustomerIdIndexImport } from './routes/connect/customers/$customerId/index'
import { Route as CashTicketsTicketIdIndexImport } from './routes/cash/tickets/$ticketId/index'
import { Route as CashTerminalCashRegisterIdIndexImport } from './routes/cash/terminal/$cashRegisterId/index'
import { Route as CashConvertToInvoiceTicketIdIndexImport } from './routes/cash/convert-to-invoice/$ticketId/index'
import { Route as ConnectQuotesQuoteIdEditImport } from './routes/connect/quotes/$quoteId/edit'
import { Route as ConnectOrdersOrderIdEditImport } from './routes/connect/orders/$orderId/edit'
import { Route as ConnectInvoicesInvoiceIdEditImport } from './routes/connect/invoices/$invoiceId/edit'
import { Route as ConnectCustomersCustomerIdEditImport } from './routes/connect/customers/$customerId/edit'

// Create/Update Routes

const SetupRoute = SetupImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StockIndexRoute = StockIndexImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRoute,
} as any)

const StickIndexRoute = StickIndexImport.update({
  id: '/stick/',
  path: '/stick/',
  getParentRoute: () => rootRoute,
} as any)

const StatsIndexRoute = StatsIndexImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRoute,
} as any)

const SiteIndexRoute = SiteIndexImport.update({
  id: '/site/',
  path: '/site/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const InventoryAppposIndexRoute = InventoryAppposIndexImport.update({
  id: '/inventory-apppos/',
  path: '/inventory-apppos/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectIndexRoute = ConnectIndexImport.update({
  id: '/connect/',
  path: '/connect/',
  getParentRoute: () => rootRoute,
} as any)

const CashIndexRoute = CashIndexImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => rootRoute,
} as any)

const SiteMenuRoute = SiteMenuImport.update({
  id: '/site/menu',
  path: '/site/menu',
  getParentRoute: () => rootRoute,
} as any)

const SiteCatalogueRoute = SiteCatalogueImport.update({
  id: '/site/catalogue',
  path: '/site/catalogue',
  getParentRoute: () => rootRoute,
} as any)

const SettingsUsersRoute = SettingsUsersImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRoute,
} as any)

const SettingsSmtpRoute = SettingsSmtpImport.update({
  id: '/settings/smtp',
  path: '/settings/smtp',
  getParentRoute: () => rootRoute,
} as any)

const SettingsSecretsRoute = SettingsSecretsImport.update({
  id: '/settings/secrets',
  path: '/settings/secrets',
  getParentRoute: () => rootRoute,
} as any)

const SettingsCompaniesRoute = SettingsCompaniesImport.update({
  id: '/settings/companies',
  path: '/settings/companies',
  getParentRoute: () => rootRoute,
} as any)

const CashConfigRoute = CashConfigImport.update({
  id: '/cash/config',
  path: '/cash/config',
  getParentRoute: () => rootRoute,
} as any)

const StockProduitsIndexRoute = StockProduitsIndexImport.update({
  id: '/stock/produits/',
  path: '/stock/produits/',
  getParentRoute: () => rootRoute,
} as any)

const StockMarquesIndexRoute = StockMarquesIndexImport.update({
  id: '/stock/marques/',
  path: '/stock/marques/',
  getParentRoute: () => rootRoute,
} as any)

const StockInventaireIndexRoute = StockInventaireIndexImport.update({
  id: '/stock/inventaire/',
  path: '/stock/inventaire/',
  getParentRoute: () => rootRoute,
} as any)

const StockFournisseursIndexRoute = StockFournisseursIndexImport.update({
  id: '/stock/fournisseurs/',
  path: '/stock/fournisseurs/',
  getParentRoute: () => rootRoute,
} as any)

const StockCategoriesIndexRoute = StockCategoriesIndexImport.update({
  id: '/stock/categories/',
  path: '/stock/categories/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectQuotesIndexRoute = ConnectQuotesIndexImport.update({
  id: '/connect/quotes/',
  path: '/connect/quotes/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectOrdersIndexRoute = ConnectOrdersIndexImport.update({
  id: '/connect/orders/',
  path: '/connect/orders/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectInvoicesIndexRoute = ConnectInvoicesIndexImport.update({
  id: '/connect/invoices/',
  path: '/connect/invoices/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectCustomersIndexRoute = ConnectCustomersIndexImport.update({
  id: '/connect/customers/',
  path: '/connect/customers/',
  getParentRoute: () => rootRoute,
} as any)

const CashTicketsIndexRoute = CashTicketsIndexImport.update({
  id: '/cash/tickets/',
  path: '/cash/tickets/',
  getParentRoute: () => rootRoute,
} as any)

const CashTerminalIndexRoute = CashTerminalIndexImport.update({
  id: '/cash/terminal/',
  path: '/cash/terminal/',
  getParentRoute: () => rootRoute,
} as any)

const CashRapportZIndexRoute = CashRapportZIndexImport.update({
  id: '/cash/rapport-z/',
  path: '/cash/rapport-z/',
  getParentRoute: () => rootRoute,
} as any)

const CashProductsIndexRoute = CashProductsIndexImport.update({
  id: '/cash/products/',
  path: '/cash/products/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectQuotesNewRoute = ConnectQuotesNewImport.update({
  id: '/connect/quotes/new',
  path: '/connect/quotes/new',
  getParentRoute: () => rootRoute,
} as any)

const ConnectOrdersNewRoute = ConnectOrdersNewImport.update({
  id: '/connect/orders/new',
  path: '/connect/orders/new',
  getParentRoute: () => rootRoute,
} as any)

const ConnectInvoicesNewRoute = ConnectInvoicesNewImport.update({
  id: '/connect/invoices/new',
  path: '/connect/invoices/new',
  getParentRoute: () => rootRoute,
} as any)

const ConnectCustomersNewRoute = ConnectCustomersNewImport.update({
  id: '/connect/customers/new',
  path: '/connect/customers/new',
  getParentRoute: () => rootRoute,
} as any)

const ConnectQuotesQuoteIdIndexRoute = ConnectQuotesQuoteIdIndexImport.update({
  id: '/connect/quotes/$quoteId/',
  path: '/connect/quotes/$quoteId/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectOrdersOrderIdIndexRoute = ConnectOrdersOrderIdIndexImport.update({
  id: '/connect/orders/$orderId/',
  path: '/connect/orders/$orderId/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectInvoicesInvoiceIdIndexRoute =
  ConnectInvoicesInvoiceIdIndexImport.update({
    id: '/connect/invoices/$invoiceId/',
    path: '/connect/invoices/$invoiceId/',
    getParentRoute: () => rootRoute,
  } as any)

const ConnectCustomersCustomerIdIndexRoute =
  ConnectCustomersCustomerIdIndexImport.update({
    id: '/connect/customers/$customerId/',
    path: '/connect/customers/$customerId/',
    getParentRoute: () => rootRoute,
  } as any)

const CashTicketsTicketIdIndexRoute = CashTicketsTicketIdIndexImport.update({
  id: '/cash/tickets/$ticketId/',
  path: '/cash/tickets/$ticketId/',
  getParentRoute: () => rootRoute,
} as any)

const CashTerminalCashRegisterIdIndexRoute =
  CashTerminalCashRegisterIdIndexImport.update({
    id: '/cash/terminal/$cashRegisterId/',
    path: '/cash/terminal/$cashRegisterId/',
    getParentRoute: () => rootRoute,
  } as any)

const CashConvertToInvoiceTicketIdIndexRoute =
  CashConvertToInvoiceTicketIdIndexImport.update({
    id: '/cash/convert-to-invoice/$ticketId/',
    path: '/cash/convert-to-invoice/$ticketId/',
    getParentRoute: () => rootRoute,
  } as any)

const ConnectQuotesQuoteIdEditRoute = ConnectQuotesQuoteIdEditImport.update({
  id: '/connect/quotes/$quoteId/edit',
  path: '/connect/quotes/$quoteId/edit',
  getParentRoute: () => rootRoute,
} as any)

const ConnectOrdersOrderIdEditRoute = ConnectOrdersOrderIdEditImport.update({
  id: '/connect/orders/$orderId/edit',
  path: '/connect/orders/$orderId/edit',
  getParentRoute: () => rootRoute,
} as any)

const ConnectInvoicesInvoiceIdEditRoute =
  ConnectInvoicesInvoiceIdEditImport.update({
    id: '/connect/invoices/$invoiceId/edit',
    path: '/connect/invoices/$invoiceId/edit',
    getParentRoute: () => rootRoute,
  } as any)

const ConnectCustomersCustomerIdEditRoute =
  ConnectCustomersCustomerIdEditImport.update({
    id: '/connect/customers/$customerId/edit',
    path: '/connect/customers/$customerId/edit',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupImport
      parentRoute: typeof rootRoute
    }
    '/cash/config': {
      id: '/cash/config'
      path: '/cash/config'
      fullPath: '/cash/config'
      preLoaderRoute: typeof CashConfigImport
      parentRoute: typeof rootRoute
    }
    '/settings/companies': {
      id: '/settings/companies'
      path: '/settings/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof SettingsCompaniesImport
      parentRoute: typeof rootRoute
    }
    '/settings/secrets': {
      id: '/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof SettingsSecretsImport
      parentRoute: typeof rootRoute
    }
    '/settings/smtp': {
      id: '/settings/smtp'
      path: '/settings/smtp'
      fullPath: '/settings/smtp'
      preLoaderRoute: typeof SettingsSmtpImport
      parentRoute: typeof rootRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersImport
      parentRoute: typeof rootRoute
    }
    '/site/catalogue': {
      id: '/site/catalogue'
      path: '/site/catalogue'
      fullPath: '/site/catalogue'
      preLoaderRoute: typeof SiteCatalogueImport
      parentRoute: typeof rootRoute
    }
    '/site/menu': {
      id: '/site/menu'
      path: '/site/menu'
      fullPath: '/site/menu'
      preLoaderRoute: typeof SiteMenuImport
      parentRoute: typeof rootRoute
    }
    '/cash/': {
      id: '/cash/'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/': {
      id: '/connect/'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectIndexImport
      parentRoute: typeof rootRoute
    }
    '/inventory-apppos/': {
      id: '/inventory-apppos/'
      path: '/inventory-apppos'
      fullPath: '/inventory-apppos'
      preLoaderRoute: typeof InventoryAppposIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/site/': {
      id: '/site/'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteIndexImport
      parentRoute: typeof rootRoute
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/stick/': {
      id: '/stick/'
      path: '/stick'
      fullPath: '/stick'
      preLoaderRoute: typeof StickIndexImport
      parentRoute: typeof rootRoute
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/customers/new': {
      id: '/connect/customers/new'
      path: '/connect/customers/new'
      fullPath: '/connect/customers/new'
      preLoaderRoute: typeof ConnectCustomersNewImport
      parentRoute: typeof rootRoute
    }
    '/connect/invoices/new': {
      id: '/connect/invoices/new'
      path: '/connect/invoices/new'
      fullPath: '/connect/invoices/new'
      preLoaderRoute: typeof ConnectInvoicesNewImport
      parentRoute: typeof rootRoute
    }
    '/connect/orders/new': {
      id: '/connect/orders/new'
      path: '/connect/orders/new'
      fullPath: '/connect/orders/new'
      preLoaderRoute: typeof ConnectOrdersNewImport
      parentRoute: typeof rootRoute
    }
    '/connect/quotes/new': {
      id: '/connect/quotes/new'
      path: '/connect/quotes/new'
      fullPath: '/connect/quotes/new'
      preLoaderRoute: typeof ConnectQuotesNewImport
      parentRoute: typeof rootRoute
    }
    '/cash/products/': {
      id: '/cash/products/'
      path: '/cash/products'
      fullPath: '/cash/products'
      preLoaderRoute: typeof CashProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/cash/rapport-z/': {
      id: '/cash/rapport-z/'
      path: '/cash/rapport-z'
      fullPath: '/cash/rapport-z'
      preLoaderRoute: typeof CashRapportZIndexImport
      parentRoute: typeof rootRoute
    }
    '/cash/terminal/': {
      id: '/cash/terminal/'
      path: '/cash/terminal'
      fullPath: '/cash/terminal'
      preLoaderRoute: typeof CashTerminalIndexImport
      parentRoute: typeof rootRoute
    }
    '/cash/tickets/': {
      id: '/cash/tickets/'
      path: '/cash/tickets'
      fullPath: '/cash/tickets'
      preLoaderRoute: typeof CashTicketsIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/customers/': {
      id: '/connect/customers/'
      path: '/connect/customers'
      fullPath: '/connect/customers'
      preLoaderRoute: typeof ConnectCustomersIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/invoices/': {
      id: '/connect/invoices/'
      path: '/connect/invoices'
      fullPath: '/connect/invoices'
      preLoaderRoute: typeof ConnectInvoicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/orders/': {
      id: '/connect/orders/'
      path: '/connect/orders'
      fullPath: '/connect/orders'
      preLoaderRoute: typeof ConnectOrdersIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/quotes/': {
      id: '/connect/quotes/'
      path: '/connect/quotes'
      fullPath: '/connect/quotes'
      preLoaderRoute: typeof ConnectQuotesIndexImport
      parentRoute: typeof rootRoute
    }
    '/stock/categories/': {
      id: '/stock/categories/'
      path: '/stock/categories'
      fullPath: '/stock/categories'
      preLoaderRoute: typeof StockCategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/stock/fournisseurs/': {
      id: '/stock/fournisseurs/'
      path: '/stock/fournisseurs'
      fullPath: '/stock/fournisseurs'
      preLoaderRoute: typeof StockFournisseursIndexImport
      parentRoute: typeof rootRoute
    }
    '/stock/inventaire/': {
      id: '/stock/inventaire/'
      path: '/stock/inventaire'
      fullPath: '/stock/inventaire'
      preLoaderRoute: typeof StockInventaireIndexImport
      parentRoute: typeof rootRoute
    }
    '/stock/marques/': {
      id: '/stock/marques/'
      path: '/stock/marques'
      fullPath: '/stock/marques'
      preLoaderRoute: typeof StockMarquesIndexImport
      parentRoute: typeof rootRoute
    }
    '/stock/produits/': {
      id: '/stock/produits/'
      path: '/stock/produits'
      fullPath: '/stock/produits'
      preLoaderRoute: typeof StockProduitsIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/customers/$customerId/edit': {
      id: '/connect/customers/$customerId/edit'
      path: '/connect/customers/$customerId/edit'
      fullPath: '/connect/customers/$customerId/edit'
      preLoaderRoute: typeof ConnectCustomersCustomerIdEditImport
      parentRoute: typeof rootRoute
    }
    '/connect/invoices/$invoiceId/edit': {
      id: '/connect/invoices/$invoiceId/edit'
      path: '/connect/invoices/$invoiceId/edit'
      fullPath: '/connect/invoices/$invoiceId/edit'
      preLoaderRoute: typeof ConnectInvoicesInvoiceIdEditImport
      parentRoute: typeof rootRoute
    }
    '/connect/orders/$orderId/edit': {
      id: '/connect/orders/$orderId/edit'
      path: '/connect/orders/$orderId/edit'
      fullPath: '/connect/orders/$orderId/edit'
      preLoaderRoute: typeof ConnectOrdersOrderIdEditImport
      parentRoute: typeof rootRoute
    }
    '/connect/quotes/$quoteId/edit': {
      id: '/connect/quotes/$quoteId/edit'
      path: '/connect/quotes/$quoteId/edit'
      fullPath: '/connect/quotes/$quoteId/edit'
      preLoaderRoute: typeof ConnectQuotesQuoteIdEditImport
      parentRoute: typeof rootRoute
    }
    '/cash/convert-to-invoice/$ticketId/': {
      id: '/cash/convert-to-invoice/$ticketId/'
      path: '/cash/convert-to-invoice/$ticketId'
      fullPath: '/cash/convert-to-invoice/$ticketId'
      preLoaderRoute: typeof CashConvertToInvoiceTicketIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/cash/terminal/$cashRegisterId/': {
      id: '/cash/terminal/$cashRegisterId/'
      path: '/cash/terminal/$cashRegisterId'
      fullPath: '/cash/terminal/$cashRegisterId'
      preLoaderRoute: typeof CashTerminalCashRegisterIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/cash/tickets/$ticketId/': {
      id: '/cash/tickets/$ticketId/'
      path: '/cash/tickets/$ticketId'
      fullPath: '/cash/tickets/$ticketId'
      preLoaderRoute: typeof CashTicketsTicketIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/customers/$customerId/': {
      id: '/connect/customers/$customerId/'
      path: '/connect/customers/$customerId'
      fullPath: '/connect/customers/$customerId'
      preLoaderRoute: typeof ConnectCustomersCustomerIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/invoices/$invoiceId/': {
      id: '/connect/invoices/$invoiceId/'
      path: '/connect/invoices/$invoiceId'
      fullPath: '/connect/invoices/$invoiceId'
      preLoaderRoute: typeof ConnectInvoicesInvoiceIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/orders/$orderId/': {
      id: '/connect/orders/$orderId/'
      path: '/connect/orders/$orderId'
      fullPath: '/connect/orders/$orderId'
      preLoaderRoute: typeof ConnectOrdersOrderIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/connect/quotes/$quoteId/': {
      id: '/connect/quotes/$quoteId/'
      path: '/connect/quotes/$quoteId'
      fullPath: '/connect/quotes/$quoteId'
      preLoaderRoute: typeof ConnectQuotesQuoteIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash/config': typeof CashConfigRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/smtp': typeof SettingsSmtpRoute
  '/settings/users': typeof SettingsUsersRoute
  '/site/catalogue': typeof SiteCatalogueRoute
  '/site/menu': typeof SiteMenuRoute
  '/cash': typeof CashIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/inventory-apppos': typeof InventoryAppposIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/site': typeof SiteIndexRoute
  '/stats': typeof StatsIndexRoute
  '/stick': typeof StickIndexRoute
  '/stock': typeof StockIndexRoute
  '/connect/customers/new': typeof ConnectCustomersNewRoute
  '/connect/invoices/new': typeof ConnectInvoicesNewRoute
  '/connect/orders/new': typeof ConnectOrdersNewRoute
  '/connect/quotes/new': typeof ConnectQuotesNewRoute
  '/cash/products': typeof CashProductsIndexRoute
  '/cash/rapport-z': typeof CashRapportZIndexRoute
  '/cash/terminal': typeof CashTerminalIndexRoute
  '/cash/tickets': typeof CashTicketsIndexRoute
  '/connect/customers': typeof ConnectCustomersIndexRoute
  '/connect/invoices': typeof ConnectInvoicesIndexRoute
  '/connect/orders': typeof ConnectOrdersIndexRoute
  '/connect/quotes': typeof ConnectQuotesIndexRoute
  '/stock/categories': typeof StockCategoriesIndexRoute
  '/stock/fournisseurs': typeof StockFournisseursIndexRoute
  '/stock/inventaire': typeof StockInventaireIndexRoute
  '/stock/marques': typeof StockMarquesIndexRoute
  '/stock/produits': typeof StockProduitsIndexRoute
  '/connect/customers/$customerId/edit': typeof ConnectCustomersCustomerIdEditRoute
  '/connect/invoices/$invoiceId/edit': typeof ConnectInvoicesInvoiceIdEditRoute
  '/connect/orders/$orderId/edit': typeof ConnectOrdersOrderIdEditRoute
  '/connect/quotes/$quoteId/edit': typeof ConnectQuotesQuoteIdEditRoute
  '/cash/convert-to-invoice/$ticketId': typeof CashConvertToInvoiceTicketIdIndexRoute
  '/cash/terminal/$cashRegisterId': typeof CashTerminalCashRegisterIdIndexRoute
  '/cash/tickets/$ticketId': typeof CashTicketsTicketIdIndexRoute
  '/connect/customers/$customerId': typeof ConnectCustomersCustomerIdIndexRoute
  '/connect/invoices/$invoiceId': typeof ConnectInvoicesInvoiceIdIndexRoute
  '/connect/orders/$orderId': typeof ConnectOrdersOrderIdIndexRoute
  '/connect/quotes/$quoteId': typeof ConnectQuotesQuoteIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash/config': typeof CashConfigRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/smtp': typeof SettingsSmtpRoute
  '/settings/users': typeof SettingsUsersRoute
  '/site/catalogue': typeof SiteCatalogueRoute
  '/site/menu': typeof SiteMenuRoute
  '/cash': typeof CashIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/inventory-apppos': typeof InventoryAppposIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/site': typeof SiteIndexRoute
  '/stats': typeof StatsIndexRoute
  '/stick': typeof StickIndexRoute
  '/stock': typeof StockIndexRoute
  '/connect/customers/new': typeof ConnectCustomersNewRoute
  '/connect/invoices/new': typeof ConnectInvoicesNewRoute
  '/connect/orders/new': typeof ConnectOrdersNewRoute
  '/connect/quotes/new': typeof ConnectQuotesNewRoute
  '/cash/products': typeof CashProductsIndexRoute
  '/cash/rapport-z': typeof CashRapportZIndexRoute
  '/cash/terminal': typeof CashTerminalIndexRoute
  '/cash/tickets': typeof CashTicketsIndexRoute
  '/connect/customers': typeof ConnectCustomersIndexRoute
  '/connect/invoices': typeof ConnectInvoicesIndexRoute
  '/connect/orders': typeof ConnectOrdersIndexRoute
  '/connect/quotes': typeof ConnectQuotesIndexRoute
  '/stock/categories': typeof StockCategoriesIndexRoute
  '/stock/fournisseurs': typeof StockFournisseursIndexRoute
  '/stock/inventaire': typeof StockInventaireIndexRoute
  '/stock/marques': typeof StockMarquesIndexRoute
  '/stock/produits': typeof StockProduitsIndexRoute
  '/connect/customers/$customerId/edit': typeof ConnectCustomersCustomerIdEditRoute
  '/connect/invoices/$invoiceId/edit': typeof ConnectInvoicesInvoiceIdEditRoute
  '/connect/orders/$orderId/edit': typeof ConnectOrdersOrderIdEditRoute
  '/connect/quotes/$quoteId/edit': typeof ConnectQuotesQuoteIdEditRoute
  '/cash/convert-to-invoice/$ticketId': typeof CashConvertToInvoiceTicketIdIndexRoute
  '/cash/terminal/$cashRegisterId': typeof CashTerminalCashRegisterIdIndexRoute
  '/cash/tickets/$ticketId': typeof CashTicketsTicketIdIndexRoute
  '/connect/customers/$customerId': typeof ConnectCustomersCustomerIdIndexRoute
  '/connect/invoices/$invoiceId': typeof ConnectInvoicesInvoiceIdIndexRoute
  '/connect/orders/$orderId': typeof ConnectOrdersOrderIdIndexRoute
  '/connect/quotes/$quoteId': typeof ConnectQuotesQuoteIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/cash/config': typeof CashConfigRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/smtp': typeof SettingsSmtpRoute
  '/settings/users': typeof SettingsUsersRoute
  '/site/catalogue': typeof SiteCatalogueRoute
  '/site/menu': typeof SiteMenuRoute
  '/cash/': typeof CashIndexRoute
  '/connect/': typeof ConnectIndexRoute
  '/inventory-apppos/': typeof InventoryAppposIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/site/': typeof SiteIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/stick/': typeof StickIndexRoute
  '/stock/': typeof StockIndexRoute
  '/connect/customers/new': typeof ConnectCustomersNewRoute
  '/connect/invoices/new': typeof ConnectInvoicesNewRoute
  '/connect/orders/new': typeof ConnectOrdersNewRoute
  '/connect/quotes/new': typeof ConnectQuotesNewRoute
  '/cash/products/': typeof CashProductsIndexRoute
  '/cash/rapport-z/': typeof CashRapportZIndexRoute
  '/cash/terminal/': typeof CashTerminalIndexRoute
  '/cash/tickets/': typeof CashTicketsIndexRoute
  '/connect/customers/': typeof ConnectCustomersIndexRoute
  '/connect/invoices/': typeof ConnectInvoicesIndexRoute
  '/connect/orders/': typeof ConnectOrdersIndexRoute
  '/connect/quotes/': typeof ConnectQuotesIndexRoute
  '/stock/categories/': typeof StockCategoriesIndexRoute
  '/stock/fournisseurs/': typeof StockFournisseursIndexRoute
  '/stock/inventaire/': typeof StockInventaireIndexRoute
  '/stock/marques/': typeof StockMarquesIndexRoute
  '/stock/produits/': typeof StockProduitsIndexRoute
  '/connect/customers/$customerId/edit': typeof ConnectCustomersCustomerIdEditRoute
  '/connect/invoices/$invoiceId/edit': typeof ConnectInvoicesInvoiceIdEditRoute
  '/connect/orders/$orderId/edit': typeof ConnectOrdersOrderIdEditRoute
  '/connect/quotes/$quoteId/edit': typeof ConnectQuotesQuoteIdEditRoute
  '/cash/convert-to-invoice/$ticketId/': typeof CashConvertToInvoiceTicketIdIndexRoute
  '/cash/terminal/$cashRegisterId/': typeof CashTerminalCashRegisterIdIndexRoute
  '/cash/tickets/$ticketId/': typeof CashTicketsTicketIdIndexRoute
  '/connect/customers/$customerId/': typeof ConnectCustomersCustomerIdIndexRoute
  '/connect/invoices/$invoiceId/': typeof ConnectInvoicesInvoiceIdIndexRoute
  '/connect/orders/$orderId/': typeof ConnectOrdersOrderIdIndexRoute
  '/connect/quotes/$quoteId/': typeof ConnectQuotesQuoteIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/cash/config'
    | '/settings/companies'
    | '/settings/secrets'
    | '/settings/smtp'
    | '/settings/users'
    | '/site/catalogue'
    | '/site/menu'
    | '/cash'
    | '/connect'
    | '/inventory-apppos'
    | '/settings'
    | '/site'
    | '/stats'
    | '/stick'
    | '/stock'
    | '/connect/customers/new'
    | '/connect/invoices/new'
    | '/connect/orders/new'
    | '/connect/quotes/new'
    | '/cash/products'
    | '/cash/rapport-z'
    | '/cash/terminal'
    | '/cash/tickets'
    | '/connect/customers'
    | '/connect/invoices'
    | '/connect/orders'
    | '/connect/quotes'
    | '/stock/categories'
    | '/stock/fournisseurs'
    | '/stock/inventaire'
    | '/stock/marques'
    | '/stock/produits'
    | '/connect/customers/$customerId/edit'
    | '/connect/invoices/$invoiceId/edit'
    | '/connect/orders/$orderId/edit'
    | '/connect/quotes/$quoteId/edit'
    | '/cash/convert-to-invoice/$ticketId'
    | '/cash/terminal/$cashRegisterId'
    | '/cash/tickets/$ticketId'
    | '/connect/customers/$customerId'
    | '/connect/invoices/$invoiceId'
    | '/connect/orders/$orderId'
    | '/connect/quotes/$quoteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/cash/config'
    | '/settings/companies'
    | '/settings/secrets'
    | '/settings/smtp'
    | '/settings/users'
    | '/site/catalogue'
    | '/site/menu'
    | '/cash'
    | '/connect'
    | '/inventory-apppos'
    | '/settings'
    | '/site'
    | '/stats'
    | '/stick'
    | '/stock'
    | '/connect/customers/new'
    | '/connect/invoices/new'
    | '/connect/orders/new'
    | '/connect/quotes/new'
    | '/cash/products'
    | '/cash/rapport-z'
    | '/cash/terminal'
    | '/cash/tickets'
    | '/connect/customers'
    | '/connect/invoices'
    | '/connect/orders'
    | '/connect/quotes'
    | '/stock/categories'
    | '/stock/fournisseurs'
    | '/stock/inventaire'
    | '/stock/marques'
    | '/stock/produits'
    | '/connect/customers/$customerId/edit'
    | '/connect/invoices/$invoiceId/edit'
    | '/connect/orders/$orderId/edit'
    | '/connect/quotes/$quoteId/edit'
    | '/cash/convert-to-invoice/$ticketId'
    | '/cash/terminal/$cashRegisterId'
    | '/cash/tickets/$ticketId'
    | '/connect/customers/$customerId'
    | '/connect/invoices/$invoiceId'
    | '/connect/orders/$orderId'
    | '/connect/quotes/$quoteId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/cash/config'
    | '/settings/companies'
    | '/settings/secrets'
    | '/settings/smtp'
    | '/settings/users'
    | '/site/catalogue'
    | '/site/menu'
    | '/cash/'
    | '/connect/'
    | '/inventory-apppos/'
    | '/settings/'
    | '/site/'
    | '/stats/'
    | '/stick/'
    | '/stock/'
    | '/connect/customers/new'
    | '/connect/invoices/new'
    | '/connect/orders/new'
    | '/connect/quotes/new'
    | '/cash/products/'
    | '/cash/rapport-z/'
    | '/cash/terminal/'
    | '/cash/tickets/'
    | '/connect/customers/'
    | '/connect/invoices/'
    | '/connect/orders/'
    | '/connect/quotes/'
    | '/stock/categories/'
    | '/stock/fournisseurs/'
    | '/stock/inventaire/'
    | '/stock/marques/'
    | '/stock/produits/'
    | '/connect/customers/$customerId/edit'
    | '/connect/invoices/$invoiceId/edit'
    | '/connect/orders/$orderId/edit'
    | '/connect/quotes/$quoteId/edit'
    | '/cash/convert-to-invoice/$ticketId/'
    | '/cash/terminal/$cashRegisterId/'
    | '/cash/tickets/$ticketId/'
    | '/connect/customers/$customerId/'
    | '/connect/invoices/$invoiceId/'
    | '/connect/orders/$orderId/'
    | '/connect/quotes/$quoteId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  CashConfigRoute: typeof CashConfigRoute
  SettingsCompaniesRoute: typeof SettingsCompaniesRoute
  SettingsSecretsRoute: typeof SettingsSecretsRoute
  SettingsSmtpRoute: typeof SettingsSmtpRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SiteCatalogueRoute: typeof SiteCatalogueRoute
  SiteMenuRoute: typeof SiteMenuRoute
  CashIndexRoute: typeof CashIndexRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
  InventoryAppposIndexRoute: typeof InventoryAppposIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SiteIndexRoute: typeof SiteIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  StickIndexRoute: typeof StickIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  ConnectCustomersNewRoute: typeof ConnectCustomersNewRoute
  ConnectInvoicesNewRoute: typeof ConnectInvoicesNewRoute
  ConnectOrdersNewRoute: typeof ConnectOrdersNewRoute
  ConnectQuotesNewRoute: typeof ConnectQuotesNewRoute
  CashProductsIndexRoute: typeof CashProductsIndexRoute
  CashRapportZIndexRoute: typeof CashRapportZIndexRoute
  CashTerminalIndexRoute: typeof CashTerminalIndexRoute
  CashTicketsIndexRoute: typeof CashTicketsIndexRoute
  ConnectCustomersIndexRoute: typeof ConnectCustomersIndexRoute
  ConnectInvoicesIndexRoute: typeof ConnectInvoicesIndexRoute
  ConnectOrdersIndexRoute: typeof ConnectOrdersIndexRoute
  ConnectQuotesIndexRoute: typeof ConnectQuotesIndexRoute
  StockCategoriesIndexRoute: typeof StockCategoriesIndexRoute
  StockFournisseursIndexRoute: typeof StockFournisseursIndexRoute
  StockInventaireIndexRoute: typeof StockInventaireIndexRoute
  StockMarquesIndexRoute: typeof StockMarquesIndexRoute
  StockProduitsIndexRoute: typeof StockProduitsIndexRoute
  ConnectCustomersCustomerIdEditRoute: typeof ConnectCustomersCustomerIdEditRoute
  ConnectInvoicesInvoiceIdEditRoute: typeof ConnectInvoicesInvoiceIdEditRoute
  ConnectOrdersOrderIdEditRoute: typeof ConnectOrdersOrderIdEditRoute
  ConnectQuotesQuoteIdEditRoute: typeof ConnectQuotesQuoteIdEditRoute
  CashConvertToInvoiceTicketIdIndexRoute: typeof CashConvertToInvoiceTicketIdIndexRoute
  CashTerminalCashRegisterIdIndexRoute: typeof CashTerminalCashRegisterIdIndexRoute
  CashTicketsTicketIdIndexRoute: typeof CashTicketsTicketIdIndexRoute
  ConnectCustomersCustomerIdIndexRoute: typeof ConnectCustomersCustomerIdIndexRoute
  ConnectInvoicesInvoiceIdIndexRoute: typeof ConnectInvoicesInvoiceIdIndexRoute
  ConnectOrdersOrderIdIndexRoute: typeof ConnectOrdersOrderIdIndexRoute
  ConnectQuotesQuoteIdIndexRoute: typeof ConnectQuotesQuoteIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  CashConfigRoute: CashConfigRoute,
  SettingsCompaniesRoute: SettingsCompaniesRoute,
  SettingsSecretsRoute: SettingsSecretsRoute,
  SettingsSmtpRoute: SettingsSmtpRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SiteCatalogueRoute: SiteCatalogueRoute,
  SiteMenuRoute: SiteMenuRoute,
  CashIndexRoute: CashIndexRoute,
  ConnectIndexRoute: ConnectIndexRoute,
  InventoryAppposIndexRoute: InventoryAppposIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SiteIndexRoute: SiteIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  StickIndexRoute: StickIndexRoute,
  StockIndexRoute: StockIndexRoute,
  ConnectCustomersNewRoute: ConnectCustomersNewRoute,
  ConnectInvoicesNewRoute: ConnectInvoicesNewRoute,
  ConnectOrdersNewRoute: ConnectOrdersNewRoute,
  ConnectQuotesNewRoute: ConnectQuotesNewRoute,
  CashProductsIndexRoute: CashProductsIndexRoute,
  CashRapportZIndexRoute: CashRapportZIndexRoute,
  CashTerminalIndexRoute: CashTerminalIndexRoute,
  CashTicketsIndexRoute: CashTicketsIndexRoute,
  ConnectCustomersIndexRoute: ConnectCustomersIndexRoute,
  ConnectInvoicesIndexRoute: ConnectInvoicesIndexRoute,
  ConnectOrdersIndexRoute: ConnectOrdersIndexRoute,
  ConnectQuotesIndexRoute: ConnectQuotesIndexRoute,
  StockCategoriesIndexRoute: StockCategoriesIndexRoute,
  StockFournisseursIndexRoute: StockFournisseursIndexRoute,
  StockInventaireIndexRoute: StockInventaireIndexRoute,
  StockMarquesIndexRoute: StockMarquesIndexRoute,
  StockProduitsIndexRoute: StockProduitsIndexRoute,
  ConnectCustomersCustomerIdEditRoute: ConnectCustomersCustomerIdEditRoute,
  ConnectInvoicesInvoiceIdEditRoute: ConnectInvoicesInvoiceIdEditRoute,
  ConnectOrdersOrderIdEditRoute: ConnectOrdersOrderIdEditRoute,
  ConnectQuotesQuoteIdEditRoute: ConnectQuotesQuoteIdEditRoute,
  CashConvertToInvoiceTicketIdIndexRoute:
    CashConvertToInvoiceTicketIdIndexRoute,
  CashTerminalCashRegisterIdIndexRoute: CashTerminalCashRegisterIdIndexRoute,
  CashTicketsTicketIdIndexRoute: CashTicketsTicketIdIndexRoute,
  ConnectCustomersCustomerIdIndexRoute: ConnectCustomersCustomerIdIndexRoute,
  ConnectInvoicesInvoiceIdIndexRoute: ConnectInvoicesInvoiceIdIndexRoute,
  ConnectOrdersOrderIdIndexRoute: ConnectOrdersOrderIdIndexRoute,
  ConnectQuotesQuoteIdIndexRoute: ConnectQuotesQuoteIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/setup",
        "/cash/config",
        "/settings/companies",
        "/settings/secrets",
        "/settings/smtp",
        "/settings/users",
        "/site/catalogue",
        "/site/menu",
        "/cash/",
        "/connect/",
        "/inventory-apppos/",
        "/settings/",
        "/site/",
        "/stats/",
        "/stick/",
        "/stock/",
        "/connect/customers/new",
        "/connect/invoices/new",
        "/connect/orders/new",
        "/connect/quotes/new",
        "/cash/products/",
        "/cash/rapport-z/",
        "/cash/terminal/",
        "/cash/tickets/",
        "/connect/customers/",
        "/connect/invoices/",
        "/connect/orders/",
        "/connect/quotes/",
        "/stock/categories/",
        "/stock/fournisseurs/",
        "/stock/inventaire/",
        "/stock/marques/",
        "/stock/produits/",
        "/connect/customers/$customerId/edit",
        "/connect/invoices/$invoiceId/edit",
        "/connect/orders/$orderId/edit",
        "/connect/quotes/$quoteId/edit",
        "/cash/convert-to-invoice/$ticketId/",
        "/cash/terminal/$cashRegisterId/",
        "/cash/tickets/$ticketId/",
        "/connect/customers/$customerId/",
        "/connect/invoices/$invoiceId/",
        "/connect/orders/$orderId/",
        "/connect/quotes/$quoteId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx"
    },
    "/cash/config": {
      "filePath": "cash/config.tsx"
    },
    "/settings/companies": {
      "filePath": "settings/companies.tsx"
    },
    "/settings/secrets": {
      "filePath": "settings/secrets.tsx"
    },
    "/settings/smtp": {
      "filePath": "settings/smtp.tsx"
    },
    "/settings/users": {
      "filePath": "settings/users.tsx"
    },
    "/site/catalogue": {
      "filePath": "site/catalogue.tsx"
    },
    "/site/menu": {
      "filePath": "site/menu.tsx"
    },
    "/cash/": {
      "filePath": "cash/index.tsx"
    },
    "/connect/": {
      "filePath": "connect/index.tsx"
    },
    "/inventory-apppos/": {
      "filePath": "inventory-apppos/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/site/": {
      "filePath": "site/index.tsx"
    },
    "/stats/": {
      "filePath": "stats/index.tsx"
    },
    "/stick/": {
      "filePath": "stick/index.tsx"
    },
    "/stock/": {
      "filePath": "stock/index.tsx"
    },
    "/connect/customers/new": {
      "filePath": "connect/customers/new.tsx"
    },
    "/connect/invoices/new": {
      "filePath": "connect/invoices/new.tsx"
    },
    "/connect/orders/new": {
      "filePath": "connect/orders/new.tsx"
    },
    "/connect/quotes/new": {
      "filePath": "connect/quotes/new.tsx"
    },
    "/cash/products/": {
      "filePath": "cash/products/index.tsx"
    },
    "/cash/rapport-z/": {
      "filePath": "cash/rapport-z/index.tsx"
    },
    "/cash/terminal/": {
      "filePath": "cash/terminal/index.tsx"
    },
    "/cash/tickets/": {
      "filePath": "cash/tickets/index.tsx"
    },
    "/connect/customers/": {
      "filePath": "connect/customers/index.tsx"
    },
    "/connect/invoices/": {
      "filePath": "connect/invoices/index.tsx"
    },
    "/connect/orders/": {
      "filePath": "connect/orders/index.tsx"
    },
    "/connect/quotes/": {
      "filePath": "connect/quotes/index.tsx"
    },
    "/stock/categories/": {
      "filePath": "stock/categories/index.tsx"
    },
    "/stock/fournisseurs/": {
      "filePath": "stock/fournisseurs/index.tsx"
    },
    "/stock/inventaire/": {
      "filePath": "stock/inventaire/index.tsx"
    },
    "/stock/marques/": {
      "filePath": "stock/marques/index.tsx"
    },
    "/stock/produits/": {
      "filePath": "stock/produits/index.tsx"
    },
    "/connect/customers/$customerId/edit": {
      "filePath": "connect/customers/$customerId/edit.tsx"
    },
    "/connect/invoices/$invoiceId/edit": {
      "filePath": "connect/invoices/$invoiceId/edit.tsx"
    },
    "/connect/orders/$orderId/edit": {
      "filePath": "connect/orders/$orderId/edit.tsx"
    },
    "/connect/quotes/$quoteId/edit": {
      "filePath": "connect/quotes/$quoteId/edit.tsx"
    },
    "/cash/convert-to-invoice/$ticketId/": {
      "filePath": "cash/convert-to-invoice/$ticketId/index.tsx"
    },
    "/cash/terminal/$cashRegisterId/": {
      "filePath": "cash/terminal/$cashRegisterId/index.tsx"
    },
    "/cash/tickets/$ticketId/": {
      "filePath": "cash/tickets/$ticketId/index.tsx"
    },
    "/connect/customers/$customerId/": {
      "filePath": "connect/customers/$customerId/index.tsx"
    },
    "/connect/invoices/$invoiceId/": {
      "filePath": "connect/invoices/$invoiceId/index.tsx"
    },
    "/connect/orders/$orderId/": {
      "filePath": "connect/orders/$orderId/index.tsx"
    },
    "/connect/quotes/$quoteId/": {
      "filePath": "connect/quotes/$quoteId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
