// frontend/modules/cash/components/reports/RapportZPage.tsx

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Separator } from '@/components/ui/separator'
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from '@/components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useActiveCompany } from '@/lib/ActiveCompanyProvider'
import type { RapportZ } from '@/lib/types/cash.types'
import {
	CUSTOMER_TYPE_EREPORTING,
	CUSTOMER_TYPE_LABELS,
	type CustomerType,
	type CustomerTypeSummary,
	aggregateEreporting,
	estZQuatreLignes,
	estZCompteLesDocuments,
	estZListeLesDocuments,
	estZSansDetailSessions,
	estZSansRapprochementEspeces,
	getPaymentMethodLabel,
} from '@/lib/types/cash.types'
import { useNavigate, useSearch } from '@tanstack/react-router'
import {
	AlertCircle,
	BarChart2,
	Calendar,
	CheckCircle2,
	FileText,
	Hash,
	Lock,
	User,
} from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { CashModuleShell } from './CashModuleShell'
import { useRegisterManager } from './components/hooks/useRegisterManager'
import {
	PaymentMethodBreakdown,
	QuatreLignesCard,
	VATBreakdownTable,
	computeNetByMethod,
	formatCurrency,
	formatDateTime,
	isCashDifferenceSignificant,
	usePrintReport,
	useZReportGenerator,
} from './components/reports/index'

const CUSTOMER_TYPE_ORDER: CustomerType[] = [
	'individual',
	'professional',
	'administration',
	'association',
]

export function RapportZPage() {
	const { activeCompanyId } = useActiveCompany()
	const navigate = useNavigate()

	// 🆕 Search params optionnels venant de la modale de fermeture de session
	// (bouton "Clôturer et générer le Z") : permet d'arriver ici avec la
	// caisse + la date déjà sélectionnées, et de lancer la génération seul.
	const search = useSearch({ from: '/cash/rapport-z/' }) as {
		register?: string
		date?: string
		autoGenerate?: boolean
	}

	const [selectedDate, setSelectedDate] = useState<string>(
		search.date || new Date().toISOString().split('T')[0],
	)
	const [activeTab, setActiveTab] = useState<'generate' | 'history'>('generate')

	const {
		registers,
		isRegistersLoading,
		selectedRegisterId,
		setSelectedRegisterId,
	} = useRegisterManager({ ownerCompanyId: activeCompanyId ?? undefined })

	// Pré-sélectionne la caisse demandée dès qu'elle est disponible dans la liste
	const hasAppliedRegisterFromSearch = useRef(false)
	useEffect(() => {
		if (hasAppliedRegisterFromSearch.current) return
		if (!search.register) return
		if (!registers?.length) return
		const match = registers.find((r) => r.id === search.register)
		if (match) {
			setSelectedRegisterId(match.id)
			hasAppliedRegisterFromSearch.current = true
		}
	}, [search.register, registers, setSelectedRegisterId])

	const {
		rapportZ,
		isLoadingRapport,
		isError,
		error,
		checkResult,
		isLoadingCheck,
		zReportsList,
		handleGenerate,
		setShouldGenerate,
	} = useZReportGenerator({
		selectedRegisterId: selectedRegisterId ?? '',
		selectedDate,
	})

	// 🆕 Déclenche automatiquement la génération une fois que la caisse
	// et la date demandées sont en place et que la vérification est connue.
	const hasAutoGenerated = useRef(false)
	useEffect(() => {
		if (!search.autoGenerate) return
		if (hasAutoGenerated.current) return
		if (!selectedRegisterId || selectedRegisterId !== search.register) return
		if (selectedDate !== search.date) return
		if (isLoadingCheck) return
		if (!checkResult) return
		if (!checkResult.exists && !checkResult.can_generate) return

		hasAutoGenerated.current = true
		handleGenerate()

		// Nettoie les search params pour éviter de relancer la génération
		// si l'utilisateur recharge la page ou navigue en arrière.
		navigate({
			to: '/cash/rapport-z',
			search: () => ({}),
			replace: true,
		})
	}, [
		search.autoGenerate,
		search.register,
		search.date,
		selectedRegisterId,
		selectedDate,
		isLoadingCheck,
		checkResult,
		handleGenerate,
		navigate,
	])

	const { handlePrint, handleExport } = usePrintReport()
	const handleExportWithRapport = useCallback(() => {
		handleExport(rapportZ)
	}, [handleExport, rapportZ])

	return (
		<CashModuleShell
			pageTitle='Rapport Z'
			pageIcon={BarChart2}
			headerRight={
				rapportZ ? (
					<>
						<Button variant='outline' size='sm' onClick={handlePrint}>
							Imprimer
						</Button>
						<Button
							variant='outline'
							size='sm'
							onClick={handleExportWithRapport}
						>
							Exporter
						</Button>
					</>
				) : undefined
			}
		>
			<div className='container mx-auto px-6 py-8'>
				<Tabs
					value={activeTab}
					onValueChange={(v) => setActiveTab(v as 'generate' | 'history')}
				>
					<TabsList className='mb-6'>
						<TabsTrigger value='generate'>
							<FileText className='h-4 w-4 mr-2' />
							Générer un rapport
						</TabsTrigger>
						<TabsTrigger value='history'>
							<Calendar className='h-4 w-4 mr-2' />
							Historique
						</TabsTrigger>
					</TabsList>

					{/* TAB: GÉNÉRER */}
					<TabsContent value='generate'>
						<Card className='mb-6'>
							<CardHeader>
								<CardTitle className='text-base'>Sélection</CardTitle>
								<CardDescription>
									Choisissez la caisse et la date pour générer le rapport Z
								</CardDescription>
							</CardHeader>
							<CardContent>
								<div className='grid grid-cols-4 gap-4'>
									<div className='space-y-2'>
										<Label htmlFor='register'>Caisse</Label>
										<select
											id='register'
											className='w-full h-10 rounded-md border bg-white px-3 text-sm'
											value={selectedRegisterId ?? ''}
											onChange={(e) => {
												setSelectedRegisterId(e.target.value)
												setShouldGenerate(false)
											}}
											disabled={isRegistersLoading}
										>
											<option value=''>Sélectionner une caisse</option>
											{registers?.map((reg) => (
												<option key={reg.id} value={reg.id}>
													{reg.code ? `${reg.code} — ${reg.name}` : reg.name}
												</option>
											))}
										</select>
									</div>

									<div className='space-y-2'>
										<Label htmlFor='date'>Date</Label>
										<Input
											id='date'
											type='date'
											value={selectedDate}
											onChange={(e) => {
												setSelectedDate(e.target.value)
												setShouldGenerate(false)
											}}
										/>
									</div>

									<div className='space-y-2'>
										<Label>Statut</Label>
										<div className='h-10 flex items-center'>
											{isLoadingCheck ? (
												<span className='text-sm text-muted-foreground'>
													Vérification...
												</span>
											) : checkResult?.exists ? (
												<Badge variant='secondary' className='gap-1'>
													<CheckCircle2 className='h-3 w-3' />
													Rapport existant
												</Badge>
											) : checkResult?.can_generate ? (
												<Badge
													variant='outline'
													className='gap-1 text-emerald-600'
												>
													<FileText className='h-3 w-3' />
													{checkResult.available_sessions} session(s)
													disponible(s)
												</Badge>
											) : (
												<Badge
													variant='outline'
													className='gap-1 text-amber-600'
												>
													<AlertCircle className='h-3 w-3' />
													Aucune session
												</Badge>
											)}
										</div>
									</div>

									<div className='flex items-end'>
										<Button
											onClick={handleGenerate}
											disabled={
												!selectedRegisterId ||
												!selectedDate ||
												isLoadingRapport ||
												(!checkResult?.exists && !checkResult?.can_generate)
											}
											className='w-full'
										>
											{isLoadingRapport
												? 'Génération...'
												: checkResult?.exists
													? 'Afficher le rapport'
													: 'Générer le rapport'}
										</Button>
									</div>
								</div>
							</CardContent>
						</Card>

						{isError && (
							<Card className='border-destructive mb-6'>
								<CardContent className='pt-6'>
									<p className='text-sm text-destructive'>
										{(error as Error)?.message ||
											'Erreur lors de la génération du rapport Z'}
									</p>
								</CardContent>
							</Card>
						)}

						{rapportZ && <RapportZDisplay rapport={rapportZ} />}
					</TabsContent>

					{/* TAB: HISTORIQUE */}
					<TabsContent value='history'>
						<Card>
							<CardHeader>
								<CardTitle className='text-base'>
									Historique des rapports Z
								</CardTitle>
								<CardDescription>
									{selectedRegisterId
										? 'Liste des rapports Z générés pour cette caisse'
										: "Sélectionnez une caisse pour voir l'historique"}
								</CardDescription>
							</CardHeader>
							<CardContent>
								{!selectedRegisterId ? (
									<p className='text-sm text-muted-foreground py-8 text-center'>
										Sélectionnez une caisse dans l'onglet "Générer un rapport"
									</p>
								) : !zReportsList?.length ? (
									<p className='text-sm text-muted-foreground py-8 text-center'>
										Aucun rapport Z pour cette caisse
									</p>
								) : (
									<Table>
										<TableHeader>
											<TableRow>
												<TableHead>Numéro</TableHead>
												<TableHead>Date</TableHead>
												<TableHead className='text-right'>Sessions</TableHead>
												<TableHead className='text-right'>Tickets</TableHead>
												<TableHead className='text-right'>Total TTC</TableHead>
												<TableHead>Généré le</TableHead>
											</TableRow>
										</TableHeader>
										<TableBody>
											{zReportsList.map((z) => (
												<TableRow
													key={z.id}
													className='cursor-pointer hover:bg-slate-50'
													onClick={() => {
														setSelectedDate(z.date.split('T')[0])
														setShouldGenerate(true)
														setActiveTab('generate')
													}}
												>
													<TableCell className='font-mono font-medium'>
														{z.number}
													</TableCell>
													<TableCell>
														{new Date(z.date).toLocaleDateString('fr-FR')}
													</TableCell>
													<TableCell className='text-right'>
														{z.sessions_count}
													</TableCell>
													<TableCell className='text-right'>
														{z.invoice_count}
													</TableCell>
													<TableCell className='text-right font-medium'>
														{formatCurrency(z.total_ttc)}
													</TableCell>
													<TableCell className='text-muted-foreground'>
														{formatDateTime(z.generated_at)}
													</TableCell>
												</TableRow>
											))}
										</TableBody>
									</Table>
								)}
							</CardContent>
						</Card>
					</TabsContent>
				</Tabs>
			</div>
		</CashModuleShell>
	)
}

// ============================================================================
// COMPOSANT D'AFFICHAGE DU RAPPORT Z
// ============================================================================

// Type étendu local pour les nouvelles données Go (optionnelles pour rétrocompat)
type DailyTotalsExtended = RapportZ['daily_totals'] & {
	by_customer_type?: Record<string, CustomerTypeSummary>
	net_ttc?: number
}

function RapportZDisplay({ rapport }: { rapport: RapportZ }) {
	const totals = rapport.daily_totals as DailyTotalsExtended
	const byCustomerType = totals.by_customer_type
	const hasCustomerTypes =
		byCustomerType && Object.keys(byCustomerType).length > 0
	const ereporting = hasCustomerTypes
		? aggregateEreporting(byCustomerType)
		: null

	// Un rapport antérieur au 23 août 2026 se relit sous SA règle : son
	// `total_ttc` est un total mêlé, et les quatre lignes n'existent pas. Le
	// présenter sous la forme du nouveau contrat lui ferait dire ce qu'il ne dit
	// pas — sur un document scellé, c'est inacceptable.
	const quatreLignes = estZQuatreLignes(totals)
	// Contrat du 27 août 2026 : le Z ne porte plus le tiroir. Un rapport scellé
	// AVANT ce contrat garde son rapprochement à l'écran — il se relit sous la
	// règle qui l'a produit.
	const sansTiroir = estZSansRapprochementEspeces(totals)
	// Contrat du 28 août 2026 : le détail par session sort du Z — une session
	// peut chevaucher plusieurs journées et le découpage affiché ne
	// correspondait pas à la période du document. Le calcul reste, l'affichage
	// part ; la statistique du module `stats` le redécoupera par journée.
	const sansDetailSessions = estZSansDetailSessions(totals)
	const compteDocuments = estZCompteLesDocuments(totals)
	// La liste vient du document lui-même, hachée à la clôture. Si elle n'y est
	// pas, on n'en reconstruit pas une : on n'affiche rien.
	const listeDocuments = estZListeLesDocuments(totals)
		? (totals.sales_documents ?? [])
		: []

	// Sur un rapport v2, la ventilation qui compte est celle du TOTAL encaissé :
	// `by_method` ne couvre plus que la ligne 1, l'afficher sous le libellé
	// « encaissements » sous-estimerait ce qui est entré en caisse.
	const salesByMethod = quatreLignes
		? (totals.collected_by_method ?? totals.by_method ?? {})
		: (totals.by_method ?? {})
	const refundsByMethod = totals.refunds_by_method
	// ⚠️ Sur un rapport v2, `collected_by_method` déduit DÉJÀ les remboursements :
	// c'est la ventilation du total encaissé, pas celle des ventes. Lui
	// réappliquer computeNetByMethod les retrancherait une seconde fois.
	const netByMethod = quatreLignes
		? undefined
		: (totals.net_by_method ??
			(refundsByMethod
				? computeNetByMethod(salesByMethod, refundsByMethod)
				: undefined))

	return (
		<div className='space-y-6 print:space-y-4'>
			{/* En-tête */}
			<Card>
				<CardHeader>
					<div className='flex items-center justify-between'>
						<div>
							<div className='flex items-center gap-3 mb-1'>
								<CardTitle className='text-xl'>{rapport.number}</CardTitle>
								<Badge variant='outline' className='gap-1'>
									<Lock className='h-3 w-3' />
									Verrouillé
								</Badge>
							</div>
							<CardDescription>
								{rapport.cash_register.code && (
									<span>Caisse : {rapport.cash_register.code} — </span>
								)}
								{rapport.cash_register.name} •{' '}
								{new Date(rapport.date).toLocaleDateString('fr-FR', {
									weekday: 'long',
									day: 'numeric',
									month: 'long',
									year: 'numeric',
								})}
							</CardDescription>
						</div>
						<div className='text-right'>
							<div className='text-xs text-muted-foreground'>Généré le</div>
							<div className='text-sm font-medium'>
								{formatDateTime(rapport.generated_at)}
							</div>
						</div>
					</div>
				</CardHeader>
				<CardContent>
					<div className='flex items-center gap-2 text-xs text-muted-foreground font-mono bg-slate-50 p-2 rounded'>
						<Hash className='h-3 w-3' />
						<span className='truncate'>{rapport.hash}</span>
					</div>
				</CardContent>
			</Card>

			{/* Résumé global */}
			<Card>
				<CardHeader>
					<CardTitle className='text-base'>Résumé de la journée</CardTitle>
				</CardHeader>
				<CardContent className='space-y-6'>
					{quatreLignes ? (
						<>
							<QuatreLignesCard
								lignes={{
									ventesDuJour: totals.total_ttc,
									creances: totals.collected_from_receivables_ttc ?? 0,
									acomptes: totals.collected_deposits_ttc ?? 0,
									remboursements: totals.refunds_ttc ?? 0,
									encaisse: totals.collected_ttc ?? totals.total_ttc,
								}}
								tvaVentesDuJour={totals.total_tva}
							/>
							<div
								className={
									compteDocuments
										? 'grid grid-cols-4 gap-4 text-sm'
										: 'grid grid-cols-3 gap-4 text-sm'
								}
							>
								{compteDocuments ? (
									<>
										<div>
											<div className='text-xs text-muted-foreground'>
												Tickets de caisse
											</div>
											<div className='text-lg font-medium'>
												{totals.pos_ticket_count ?? 0}
											</div>
										</div>
										<div>
											<div className='text-xs text-muted-foreground'>
												Factures hors caisse
											</div>
											<div className='text-lg font-medium'>
												{totals.external_invoice_count ?? 0}
											</div>
										</div>
									</>
								) : (
									<div>
										<div className='text-xs text-muted-foreground'>
											Sessions
										</div>
										<div className='text-lg font-medium'>
											{totals.sessions_count}
										</div>
									</div>
								)}
								<div>
									<div className='text-xs text-muted-foreground'>
										Ventes du jour (documents)
									</div>
									<div className='text-lg font-medium'>
										{totals.invoice_count}
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>
										Base HT des ventes du jour
									</div>
									<div className='text-lg font-medium'>
										{formatCurrency(totals.total_ht)}
									</div>
								</div>
							</div>
						</>
					) : (
						<>
							{/* Rapport antérieur au contrat du 23 août 2026 : présenté sous
							    la règle qui l'a produit. `total_ttc` y est un total mêlé. */}
							<div className='grid grid-cols-5 gap-4'>
								<div>
									<div className='text-xs text-muted-foreground'>Sessions</div>
									<div className='text-2xl font-bold'>
										{totals.sessions_count}
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>
										Tickets / factures
									</div>
									<div className='text-2xl font-bold'>
										{totals.invoice_count}
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>Total HT</div>
									<div className='text-2xl font-bold'>
										{formatCurrency(totals.total_ht)}
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>Total TVA</div>
									<div className='text-2xl font-bold text-blue-600'>
										{formatCurrency(totals.total_tva)}
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>Total TTC</div>
									<div className='text-2xl font-bold text-emerald-600'>
										{formatCurrency(totals.total_ttc)}
									</div>
								</div>
							</div>

							{/* Net après avoirs */}
							{totals.net_ttc !== undefined &&
								totals.net_ttc !== totals.total_ttc && (
									<div className='flex justify-between text-sm px-1'>
										<span className='text-muted-foreground'>
											Net après avoirs :
										</span>
										<span className='font-semibold text-emerald-700'>
											{formatCurrency(totals.net_ttc)}
										</span>
									</div>
								)}
						</>
					)}

					<Separator />

					{/* Ventilation par nature (e-reporting) */}
					{hasCustomerTypes && (
						<>
							<div>
								<div className='text-sm font-medium mb-3'>
									Ventes par nature (e-reporting)
								</div>
								<div className='space-y-1'>
									{CUSTOMER_TYPE_ORDER.filter((ct) => byCustomerType[ct]).map(
										(ct) => {
											const summary = byCustomerType[ct]
											const tag = CUSTOMER_TYPE_EREPORTING[ct]
											return (
												<div
													key={ct}
													className='flex items-center justify-between text-sm py-1 border-b border-border/40 last:border-0'
												>
													<div className='flex items-center gap-2'>
														<Badge
															variant='outline'
															className={
																tag === 'B2C'
																	? 'text-xs px-1.5 py-0 text-blue-700 border-blue-200'
																	: 'text-xs px-1.5 py-0 text-violet-700 border-violet-200'
															}
														>
															{tag}
														</Badge>
														<span className='text-muted-foreground'>
															{CUSTOMER_TYPE_LABELS[ct]}
														</span>
													</div>
													<div className='flex items-center gap-4'>
														<span className='text-xs text-muted-foreground'>
															{summary.count} doc.
														</span>
														<span className='font-medium w-24 text-right'>
															{formatCurrency(summary.total_ttc)}
														</span>
													</div>
												</div>
											)
										},
									)}
								</div>
							</div>
							<Separator />
						</>
					)}

					{/* TVA ventilée */}
					<div>
						<div className='text-sm font-medium mb-3'>
							Ventilation de la TVA collectée
						</div>
						<VATBreakdownTable vatByRate={totals.vat_by_rate} />
					</div>

					<Separator />

					{/* Encaissements / Remboursements / Net */}
					<div className='space-y-4'>
						<div>
							<div className='text-sm font-medium mb-2'>
								{quatreLignes
									? 'Total encaissé par moyen de paiement'
									: 'Encaissements par moyen'}
							</div>
							{quatreLignes && (
								<p className='text-xs text-muted-foreground mb-2'>
									Les quatre lignes réunies, remboursements déduits. C'est ce
									qui doit correspondre au tiroir et à la banque.
								</p>
							)}
							<PaymentMethodBreakdown byMethod={salesByMethod} label='' />
						</div>

						{refundsByMethod && Object.keys(refundsByMethod).length > 0 && (
							<div>
								<div className='text-sm font-medium mb-2'>
									Remboursements par moyen
								</div>
								<div className='space-y-2'>
									{Object.entries(refundsByMethod).map(([method, amount]) => (
										<div key={method} className='flex justify-between text-sm'>
											<span className='text-muted-foreground capitalize'>
												{getPaymentMethodLabel(method)}
											</span>
											<span className='font-medium text-red-600'>
												-{formatCurrency(Math.abs(amount))}
											</span>
										</div>
									))}
								</div>
							</div>
						)}

						{netByMethod && Object.keys(netByMethod).length > 0 && (
							<div>
								<div className='text-sm font-medium mb-2'>
									Net par moyen (ventes - remboursements)
								</div>
								<div className='space-y-2'>
									{Object.entries(netByMethod).map(([method, amount]) => (
										<div key={method} className='flex justify-between text-sm'>
											<span className='text-muted-foreground capitalize'>
												{getPaymentMethodLabel(method)}
											</span>
											<span
												className={`font-medium ${
													amount < 0 ? 'text-red-600' : 'text-emerald-700'
												}`}
											>
												{formatCurrency(amount)}
											</span>
										</div>
									))}
								</div>
							</div>
						)}
					</div>

					<Separator />

					{/* Espèces — retirées du Z par le contrat du 27 août 2026.
					    Le rapprochement se vérifie au comptage du tiroir
					    (CloseSessionDialog) et dans le rapport X ; son détail ira
					    au journal espèces. Les remises, elles, ne sont pas du
					    tiroir et restent. */}
					<div
						className={`grid gap-4 ${sansTiroir ? 'grid-cols-1' : 'grid-cols-4'}`}
					>
						{!sansTiroir && (
							<>
								<div>
									<div className='text-xs text-muted-foreground'>
										Espèces attendues
									</div>
									<div className='text-lg font-medium'>
										{formatCurrency(totals.total_cash_expected)}
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>
										Espèces comptées
									</div>
									<div className='text-lg font-medium'>
										{formatCurrency(totals.total_cash_counted)}
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>
										Écart total
									</div>
									<div
										className={`text-lg font-bold ${
											isCashDifferenceSignificant(totals.total_cash_difference)
												? 'text-destructive'
												: 'text-emerald-600'
										}`}
									>
										{formatCurrency(totals.total_cash_difference)}
									</div>
								</div>
							</>
						)}
						<div>
							<div className='text-xs text-muted-foreground'>Remises</div>
							<div className='text-lg font-medium text-amber-600'>
								{formatCurrency(totals.total_discounts)}
							</div>
						</div>
					</div>

					{/* Avoirs */}
					{totals.credit_notes_count > 0 && (
						<>
							<Separator />
							<div className='flex items-center gap-4 p-3 bg-red-50 rounded'>
								<div>
									<div className='text-xs text-muted-foreground'>
										Avoirs émis
									</div>
									<div className='text-lg font-medium text-red-600'>
										{totals.credit_notes_count} avoir(s)
									</div>
								</div>
								<div>
									<div className='text-xs text-muted-foreground'>
										Montant total
									</div>
									<div className='text-lg font-medium text-red-600'>
										-{formatCurrency(totals.credit_notes_total)}
									</div>
								</div>
							</div>
						</>
					)}
				</CardContent>
			</Card>

			{/* Bloc e-reporting */}
			{ereporting && (ereporting.b2c.count > 0 || ereporting.b2b.count > 0) && (
				<Card className='border-blue-200 bg-blue-50'>
					<CardContent className='pt-6'>
						<div className='flex items-center gap-2 mb-4'>
							<FileText className='h-4 w-4 text-blue-600' />
							<p className='text-sm font-medium text-blue-900'>
								Données e-reporting — obligatoire sept. 2027 (DGFiP)
							</p>
						</div>
						<div className='grid grid-cols-2 gap-3'>
							{ereporting.b2c.count > 0 && (
								<div className='bg-white rounded-md p-3 border border-blue-100'>
									<div className='flex items-center gap-1.5 mb-2'>
										<Badge
											variant='outline'
											className='text-xs px-1.5 py-0 text-blue-700 border-blue-200'
										>
											B2C
										</Badge>
										<span className='text-xs text-muted-foreground'>
											Particuliers
										</span>
									</div>
									<p className='text-lg font-semibold'>
										{formatCurrency(ereporting.b2c.total_ttc)}
									</p>
									<p className='text-xs text-muted-foreground'>
										TVA : {formatCurrency(ereporting.b2c.total_tva)} ·{' '}
										{ereporting.b2c.count} doc.
									</p>
								</div>
							)}
							{ereporting.b2b.count > 0 && (
								<div className='bg-white rounded-md p-3 border border-blue-100'>
									<div className='flex items-center gap-1.5 mb-2'>
										<Badge
											variant='outline'
											className='text-xs px-1.5 py-0 text-violet-700 border-violet-200'
										>
											B2B
										</Badge>
										<span className='text-xs text-muted-foreground'>
											Professionnels / Associations
										</span>
									</div>
									<p className='text-lg font-semibold'>
										{formatCurrency(ereporting.b2b.total_ttc)}
									</p>
									<p className='text-xs text-muted-foreground'>
										TVA : {formatCurrency(ereporting.b2b.total_tva)} ·{' '}
										{ereporting.b2b.count} doc.
									</p>
								</div>
							)}
						</div>
						<p className='text-xs text-blue-700 mt-3'>
							Ces données sont à transmettre à votre Plateforme de
							Dématérialisation Partenaire (PDP).
						</p>
					</CardContent>
				</Card>
			)}

			{/* Documents du rapport — les quatre lignes, pièce par pièce, telles
			    que le Z les a scellées. Même présentation que le journal des
			    ventes ; aucun recalcul : `sales_documents` est lue dans le
			    document et entre dans son hash. */}
			{listeDocuments.length > 0 && (
				<Card>
					<CardHeader>
						<CardTitle className='text-base'>
							Documents ({listeDocuments.length})
						</CardTitle>
					</CardHeader>
					<CardContent>
						<div className='space-y-1'>
							{listeDocuments.map((doc) => (
								<div
									key={doc.id}
									className='flex items-center gap-3 text-sm py-1 border-b last:border-0'
								>
									<span className='w-14 text-xs text-muted-foreground shrink-0'>
										{doc.heure}
									</span>
									<Badge variant='outline' className='text-xs shrink-0'>
										{doc.kind}
									</Badge>
									<span className='font-mono text-xs shrink-0'>
										{doc.number || '—'}
									</span>
									<span className='min-w-0 flex-1 truncate text-muted-foreground'>
										{doc.customer}
									</span>
									<span className='text-xs text-muted-foreground shrink-0 hidden lg:inline'>
										{doc.line}
									</span>
									<span className='w-20 text-right text-xs text-muted-foreground shrink-0'>
										{doc.method}
									</span>
									<span
										className={`w-24 text-right font-medium tabular-nums shrink-0 ${
											doc.kind === 'avoir' ? 'text-red-600' : ''
										}`}
									>
										{doc.kind === 'avoir' ? '−' : ''}
										{formatCurrency(doc.total_ttc)}
									</span>
								</div>
							))}
						</div>
					</CardContent>
				</Card>
			)}

			{/* Détail des sessions — retiré à partir de la v4 : une session peut
			    s'étendre sur plusieurs journées alors que le Z couvre la période
			    depuis la clôture précédente. Le tableau reste dans `full_report`
			    et sera relu par la statistique des sessions. */}
			{!sansDetailSessions && (
				<Card>
					<CardHeader>
						<CardTitle className='text-base'>
							Détail des sessions ({rapport.sessions.length})
						</CardTitle>
					</CardHeader>
					<CardContent>
						<div className='space-y-4'>
							{rapport.sessions.map((session, index) => (
								<div
									key={session.id}
									className='p-4 border rounded-lg space-y-3'
								>
									<div className='flex items-center justify-between'>
										<div>
											<div className='font-medium'>Session #{index + 1}</div>
											<div className='text-xs text-muted-foreground'>
												{formatDateTime(session.opened_at)} →{' '}
												{formatDateTime(session.closed_at)}
											</div>
											<div className='flex items-center gap-4 mt-1'>
												{session.opened_by_name && (
													<div className='flex items-center gap-1 text-xs text-muted-foreground'>
														<User className='h-3 w-3' />
														<span>Ouvert : </span>
														<span className='font-medium text-foreground'>
															{session.opened_by_name}
														</span>
													</div>
												)}
												{session.closed_by_name && (
													<div className='flex items-center gap-1 text-xs text-muted-foreground'>
														<User className='h-3 w-3' />
														<span>Fermé : </span>
														<span className='font-medium text-foreground'>
															{session.closed_by_name}
														</span>
													</div>
												)}
											</div>
										</div>
										<div className='text-right'>
											<div className='text-sm font-medium'>
												{session.invoice_count} tickets
											</div>
											<div className='text-xs text-muted-foreground'>
												HT : {formatCurrency(session.total_ht)} · TVA :{' '}
												{formatCurrency(session.total_tva)}
											</div>
											<div className='text-lg font-bold text-emerald-600'>
												{formatCurrency(session.total_ttc)}
											</div>
										</div>
									</div>

									{/* Espèces session — même contrat que le bloc global : le
								    tiroir sort du Z. */}
									{!sansTiroir && (
										<div className='grid grid-cols-4 gap-3 text-sm bg-slate-50 p-3 rounded'>
											<div>
												<div className='text-xs text-muted-foreground'>
													Fond de caisse
												</div>
												<div className='font-medium'>
													{formatCurrency(session.opening_float)}
												</div>
											</div>
											<div>
												<div className='text-xs text-muted-foreground'>
													Espèces attendues
												</div>
												<div className='font-medium'>
													{formatCurrency(session.expected_cash_total)}
												</div>
											</div>
											<div>
												<div className='text-xs text-muted-foreground'>
													Espèces comptées
												</div>
												<div className='font-medium'>
													{formatCurrency(session.counted_cash_total)}
												</div>
											</div>
											<div>
												<div className='text-xs text-muted-foreground'>
													Écart
												</div>
												<div
													className={`font-medium ${
														isCashDifferenceSignificant(session.cash_difference)
															? 'text-destructive'
															: 'text-emerald-600'
													}`}
												>
													{formatCurrency(session.cash_difference)}
												</div>
											</div>
										</div>
									)}

									{/* TVA session */}
									{session.vat_by_rate &&
										Object.keys(session.vat_by_rate).length > 0 && (
											<div className='text-sm'>
												<div className='text-xs text-muted-foreground mb-2'>
													TVA collectée
												</div>
												<div className='grid grid-cols-4 gap-2'>
													{Object.entries(session.vat_by_rate).map(
														([rate, detail]) => (
															<div key={rate} className='flex justify-between'>
																<span className='text-muted-foreground'>
																	{rate}%
																</span>
																<span className='font-medium'>
																	{formatCurrency(detail.vat_amount)}
																</span>
															</div>
														),
													)}
												</div>
											</div>
										)}

									{/* Moyens de paiement session */}
									{session.totals_by_method &&
										Object.keys(session.totals_by_method).length > 0 && (
											<div className='text-sm'>
												<PaymentMethodBreakdown
													byMethod={session.totals_by_method}
													label='Par moyen de paiement'
												/>
											</div>
										)}
								</div>
							))}
						</div>
					</CardContent>
				</Card>
			)}

			{/* Note de verrouillage */}
			<Card className='border-amber-200 bg-amber-50'>
				<CardContent className='pt-6'>
					<div className='flex items-start gap-3'>
						<Lock className='h-5 w-5 text-amber-600 mt-0.5' />
						<div className='flex-1'>
							<p className='text-sm font-medium text-amber-900'>
								{rapport.note}
							</p>
							<p className='text-xs text-amber-700 mt-1'>
								Ce rapport est une capture figée de l'activité de la journée. Il
								ne peut être ni modifié ni supprimé (conformité NF525).
							</p>
							<p className='text-xs text-amber-700 mt-1 font-mono'>
								Hash de vérification : {rapport.hash.substring(0, 16)}...
							</p>
						</div>
					</div>
				</CardContent>
			</Card>
		</div>
	)
}
