// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSetupStatus() {
	return window['go']['main']['App']['CheckSetupStatus']()
}

export function GetAppVersion() {
	return window['go']['main']['App']['GetAppVersion']()
}

export function GetDataPath() {
	return window['go']['main']['App']['GetDataPath']()
}

export function GetNetworkInfo() {
	return window['go']['main']['App']['GetNetworkInfo']()
}

export function ListPrinters() {
	return window['go']['main']['App']['ListPrinters']()
}

export function ListSerialPorts() {
	return window['go']['main']['App']['ListSerialPorts']()
}

export function MinimizeToTray() {
	return window['go']['main']['App']['MinimizeToTray']()
}

export function OpenCashDrawer(arg1) {
	return window['go']['main']['App']['OpenCashDrawer'](arg1)
}

export function OpenFileDialog(arg1, arg2) {
	return window['go']['main']['App']['OpenFileDialog'](arg1, arg2)
}

export function PrintPosReceipt(arg1) {
	return window['go']['main']['App']['PrintPosReceipt'](arg1)
}

export function Quit() {
	return window['go']['main']['App']['Quit']()
}

export function ShowNotification(arg1, arg2) {
	return window['go']['main']['App']['ShowNotification'](arg1, arg2)
}

export function SendDisplayText(arg1) {
	return window['go']['main']['App']['SendDisplayText'](arg1)
}

export function TestDisplay(arg1) {
	return window['go']['main']['App']['TestDisplay'](arg1)
}

export function CheckForUpdates() {
	return window['go']['main']['App']['CheckForUpdates']()
}

export function DownloadAndInstallUpdate(arg1) {
	return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1)
}

// ✅ Nouvelles fonctions pour notifications distantes
export function FetchRemoteNotifications() {
	return window['go']['main']['App']['FetchRemoteNotifications']()
}

export function MarkRemoteNotificationRead(arg1) {
	return window['go']['main']['App']['MarkRemoteNotificationRead'](arg1)
}
