// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSetupStatus():Promise<boolean>;

export function GetAppVersion():Promise<string>;

export function GetDataPath():Promise<string>;

export function MinimizeToTray():Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function Quit():Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;
