// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSetupStatus(): Promise<boolean>

export function GetAppVersion(): Promise<string>

export function GetDataPath(): Promise<string>

export function GetNetworkInfo(): Promise<{ [key: string]: any }>

export function ListPrinters(): Promise<Array<string>>

export function MinimizeToTray(): Promise<void>

export function OpenCashDrawer(arg1: {
	printerName: string
	width: number
}): Promise<void>

export function OpenFileDialog(
	arg1: string,
	arg2: Array<string>,
): Promise<string>

export function PrintPosReceipt(arg1: {
	printerName: string
	width: number
	receipt: any
}): Promise<void>

export function Quit(): Promise<void>

export function ShowNotification(arg1: string, arg2: string): Promise<void>

export function CheckForUpdates(): Promise<{
	available: boolean
	version: string
	downloadUrl: string
	releaseNotes: string
	publishedAt: string
	currentVersion: string
}>

export function DownloadAndInstallUpdate(arg1: string): Promise<void>
